[tool.poetry]
name = "multi-agent-frontend-dev"
version = "0.1.0"
description = ""
authors = ["Lasse, David, Benedikt, Eric"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
